# -*- coding: utf-8 -*-
"""AI Study Assistant-with mail

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrHLUGsh-QMlhAi8tiZrh_doO6Xt3ETq
"""

# ============================================================
# 🤖 LANGGRAPH AI STUDY ASSISTANT
# 📧 SEND RESULT TO YOUR GMAIL
# ============================================================

!pip install -q langgraph

from typing import TypedDict
from langgraph.graph import StateGraph, START, END

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from getpass import getpass


# ============================================================
# 1. STATE
# ============================================================

class StudyState(TypedDict):
    topic: str
    level: str
    question: str
    explanation: str
    quiz: str
    score: int
    feedback: str


# ============================================================
# 2. ANALYZE TOPIC
# ============================================================

def analyze_topic(state):

    topic = state["topic"].lower()

    if "machine learning" in topic:
        level = "Technical"

    elif "python" in topic:
        level = "Programming"

    elif "artificial intelligence" in topic or "ai" in topic:
        level = "Technical"

    elif "deep learning" in topic:
        level = "Technical"

    else:
        level = "General"

    print("\n🔍 Analyzing topic...")

    return {"level": level}


# ============================================================
# 3. GENERATE EXPLANATION
# ============================================================

def explain_topic(state):

    topic = state["topic"]

    explanations = {
        "machine learning":
        "Machine Learning is a branch of Artificial Intelligence where computers learn patterns from data and use those patterns to make predictions or decisions.",

        "python":
        "Python is a high-level programming language known for its simple syntax, readability and large collection of libraries.",

        "artificial intelligence":
        "Artificial Intelligence is the field of creating computer systems capable of performing tasks that normally require human intelligence.",

        "ai":
        "Artificial Intelligence enables computers to perform tasks such as learning, reasoning, recognizing patterns and making decisions.",

        "deep learning":
        "Deep Learning is a branch of Machine Learning that uses multi-layer neural networks to learn complex patterns from data."
    }

    explanation = explanations.get(
        topic.lower(),
        f"{topic} is an important concept that can be studied through its principles, applications and examples."
    )

    print("\n📚 Generating explanation...")

    return {"explanation": explanation}


# ============================================================
# 4. GENERATE QUIZ
# ============================================================

def generate_quiz(state):

    topic = state["topic"]

    quiz = f"""
Quiz: {topic}

Question:
What is the main purpose or concept of {topic}?

A) Understanding and applying its fundamental concepts
B) Only playing games
C) Only designing websites
D) None of the above

Correct Answer: A
"""

    print("\n📝 Generating quiz...")

    return {"quiz": quiz}


# ============================================================
# 5. CHECK ANSWER
# ============================================================

def check_answer(state):

    print("\n✅ Checking answer...")

    # Demo score
    score = 10

    return {"score": score}


# ============================================================
# 6. FEEDBACK
# ============================================================

def generate_feedback(state):

    score = state["score"]

    if score >= 8:
        message = "🎉 Excellent! You understood the topic very well."

    elif score >= 5:
        message = "👍 Good job! A little more practice will help."

    else:
        message = "📖 Keep practicing and review the topic again."

    print("\n💬 Generating feedback...")

    return {"feedback": message}


# ============================================================
# 7. SEND EMAIL
# ============================================================

def send_email(state):

    print("\n")
    print("=" * 60)
    print("📧 EMAIL SETUP")
    print("=" * 60)

    # ONLY ONE EMAIL ADDRESS
    gmail_address = input(
        "\nEnter your Gmail address: "
    )

    print(
        "\nEnter your Gmail App Password."
    )

    print(
        "The password will NOT be displayed."
    )

    app_password = getpass(
        "Gmail App Password: "
    )

    # Email subject
    subject = (
        "AI Study Assistant - "
        + state["topic"]
    )

    # Email content
    body = f"""
🤖 AI STUDY ASSISTANT
========================================

📌 TOPIC
{state["topic"]}

📊 LEVEL
{state["level"]}

----------------------------------------

📚 EXPLANATION

{state["explanation"]}

----------------------------------------

📝 QUIZ

{state["quiz"]}

----------------------------------------

🏆 SCORE

{state["score"]} / 10

----------------------------------------

💬 FEEDBACK

{state["feedback"]}

========================================

Generated using LangGraph
"""

    # Create email
    message = MIMEMultipart()

    message["From"] = gmail_address
    message["To"] = gmail_address
    message["Subject"] = subject

    message.attach(
        MIMEText(
            body,
            "plain",
            "utf-8"
        )
    )

    try:

        print("\n📡 Connecting to Gmail...")

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        print("🔐 Logging into Gmail...")

        server.login(
            gmail_address,
            app_password
        )

        print("📨 Sending email...")

        server.sendmail(
            gmail_address,
            gmail_address,
            message.as_string()
        )

        server.quit()

        print("\n" + "=" * 60)
        print("✅ EMAIL SENT SUCCESSFULLY!")
        print("=" * 60)

        print(
            f"\n📩 Result sent to: {gmail_address}"
        )

    except Exception as error:

        print("\n" + "=" * 60)
        print("❌ EMAIL SENDING FAILED")
        print("=" * 60)

        print("\nError:")
        print(error)

        print("\nCheck these:")
        print("1. Gmail address is correct")
        print("2. 2-Step Verification is enabled")
        print("3. You are using a Gmail App Password")
        print("4. You did NOT use your normal Gmail password")

    return {}


# ============================================================
# 8. CREATE LANGGRAPH
# ============================================================

print("\n🔧 Creating LangGraph...")

builder = StateGraph(StudyState)

builder.add_node(
    "analyze",
    analyze_topic
)

builder.add_node(
    "explain",
    explain_topic
)

builder.add_node(
    "quiz",
    generate_quiz
)

builder.add_node(
    "check",
    check_answer
)

builder.add_node(
    "feedback",
    generate_feedback
)

builder.add_node(
    "send_email",
    send_email
)


# ============================================================
# 9. GRAPH FLOW
# ============================================================

builder.add_edge(
    START,
    "analyze"
)

builder.add_edge(
    "analyze",
    "explain"
)

builder.add_edge(
    "explain",
    "quiz"
)

builder.add_edge(
    "quiz",
    "check"
)

builder.add_edge(
    "check",
    "feedback"
)

builder.add_edge(
    "feedback",
    "send_email"
)

builder.add_edge(
    "send_email",
    END
)


# ============================================================
# 10. COMPILE
# ============================================================

graph = builder.compile()

print("✅ LangGraph compiled successfully!")


# ============================================================
# 11. USER INPUT
# ============================================================

print("\n")
print("=" * 60)
print("🤖 AI STUDY ASSISTANT")
print("=" * 60)

topic = input(
    "\nEnter topic: "
)


# ============================================================
# 12. INITIAL STATE
# ============================================================

initial_state = {

    "topic": topic,

    "level": "",

    "question": "",

    "explanation": "",

    "quiz": "",

    "score": 0,

    "feedback": ""
}


# ============================================================
# 13. RUN GRAPH
# ============================================================

print("\n🚀 Running LangGraph...")

result = graph.invoke(
    initial_state
)


# ============================================================
# 14. DISPLAY RESULT
# ============================================================

print("\n")
print("=" * 60)
print("🎯 FINAL RESULT")
print("=" * 60)

print("\n📌 TOPIC:")
print(result["topic"])

print("\n📊 LEVEL:")
print(result["level"])

print("\n📚 EXPLANATION:")
print(result["explanation"])

print("\n📝 QUIZ:")
print(result["quiz"])

print("\n🏆 SCORE:")
print(
    result["score"],
    "/ 10"
)

print("\n💬 FEEDBACK:")
print(result["feedback"])

print("\n")
print("=" * 60)
print("✅ COMPLETE")
print("=" * 60)